# Generated by Django 6.0.3 on 2026-05-01 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('states', models.TextField(help_text='Comma-separated state names this zone covers (case-insensitive).')),
                ('country', models.CharField(default='India', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_above', models.DecimalField(blank=True, decimal_places=2, help_text='Subtotal threshold above which shipping is free.', max_digits=10, null=True)),
                ('estimated_days_min', models.PositiveSmallIntegerField(default=3)),
                ('estimated_days_max', models.PositiveSmallIntegerField(default=7)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
