# Generated by Django 6.0.3 on 2026-05-01 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_order_courier_name_order_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rma_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_transit', 'In Transit'), ('received', 'Received'), ('refunded', 'Refunded'), ('completed', 'Completed')], db_index=True, default='requested', max_length=15)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged on arrival'), ('defective', 'Defective / not working'), ('wrong_item', 'Wrong item delivered'), ('not_as_described', 'Not as described'), ('no_longer_needed', 'No longer needed'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_reference', models.CharField(blank=True, default='', max_length=100)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('return_request', 'order_item')},
            },
        ),
    ]
