# Generated by Django 6.0.4 on 2026-04-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cancellation_reason_order_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('paypal', 'PayPal'), ('upi', 'UPI'), ('card', 'Credit / Debit Card'), ('netbanking', 'Net Banking')], default='cod', max_length=15),
        ),
    ]
