# Generated by Django 6.0.8 on 2026-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_guest_access_token_order_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='Australia', max_length=100),
        ),
    ]
