# Generated by Django 6.0.8 on 2026-08-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_phone_max_length_20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Australia', max_length=100),
        ),
    ]
